# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.define "terraform" do |cfg|
    cfg.vm.box = "ubuntu/focal64"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Terraform"
    end
    cfg.vm.host_name = "terraform"
    cfg.vm.network "private_network", ip: "192.168.8.123"
    cfg.vm.network "forwarded_port", guest: 22, host: 60123, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
  end
end